### ISSUE TITLE
RUNNING ERROR

### ISSUE THREAD

**Issue by wwzh2626** [JayParanjape/biastuning#10]
Dear author， i'm tring to run the training as you wtite in README.md. But,there is an error in the program, it seems that the file is missing.The error is as follows:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Project\\awesome_SAM\\AdaptiveSAM\\biastuning\\clip\\bpe_simple_vocab_16e6.txt.gz'
Where can i find 'bpe_simple_vocab_16e6.txt.gz'?

**Comment by JayParanjape** [comment]
Hi, Thanks for pointing out. I have uploaded it in the GDrive link in the Readme
