### ISSUE TITLE
Training failures

### ISSUE THREAD

**Issue by OSUANSDNC** [JayParanjape/biastuning#3]
Hi, thanks for your excellent work, my epoch keeps stopping at 0 when training the CHOLEC 8K dataset, have you encountered this?

**Comment by JayParanjape** [comment]
Hello, 
I did not encounter any such issues. Can you please post the error message so that I can get a better idea?

**Comment by OSUANSDNC** [comment]
Hi, thanks for your reply! I walked an epoch after waiting for about 5 minutes, is this speed normal?

**Comment by OSUANSDNC** [comment]
Hi, I'm having this problem running the generate_predictions_cholec.py file What's probably causing this Thanks in advance for your reply!
![image](https://github.com/JayParanjape/biastuning/assets/104304932/bf7ee3ca-ec5a-4086-8ddf-2a1a27c214eb)

**Comment by JayParanjape** [comment]
Oh I see why. The current code expects just one label of interest. You can change generate_predictions so that it splits the labels of interest field, or write a script that calls the python code multiple times with different labels of interest.  So the current code will run if you use just one label, for example, "Right Large Needle Driver"

**Comment by JayParanjape** [comment]
Also, i think you are using the labels for endovis 17. Cholec does not have these labels

**Comment by JayParanjape** [comment]
> Hi, thanks for your reply! I walked an epoch after waiting for about 5 minutes, is this speed normal?

It should not take this long, but i would not call it surprisingly too much amount of time as well. Also, I uploaded the model checkpoints. Feel free to use them if you don't want to train from scratch

**Comment by OSUANSDNC** [comment]
Oh! I got it, thanks for the reply!

**Comment by JayParanjape** [comment]
Hi, if there are no more issues, can you please close the issue? Thanks
