### ISSUE TITLE
 Unexpected validation performance with Cholec-Seg8k dataset

### ISSUE THREAD

**Issue by rxf-github** [JayParanjape/biastuning#5]
Dear author, I've been training your model on the Cholec-Seg8k dataset. However, I'm seeing some unusual results in TensorBoard - the validation metrics behave differently than I would expect. The training log is shown below. 
![Snipaste_2023-10-10_11-08-48](https://github.com/JayParanjape/biastuning/assets/56017553/caeeaf81-9e28-41d3-8ea7-68ed4c54c64f)

I wanted to check whether this type of validation performance is expected when training your model on the Cholec-Seg8k dataset, or if there could be an issue with my implementation. Please let me know if you have any insights into what might be going on here.

**Comment by Dirck-YHP** [comment]
Hello! I have encountered the same issue: the Dice coefficient for val keeps fluctuating, and the loss is on the rise. Could you please share how you resolved this problem?
